alter session set "_oracle_script"=true;

CREATE ROLE rl_user;
CREATE ROLE rl_admin;
CREATE ROLE rl_guest;
-------admin-------
GRANT CREATE SESSION,
	  CREATE TABLE,
	  CREATE VIEW,
	  CREATE PROCEDURE,
	  CREATE TRIGGER TO rl_admin;

CREATE USER ADMIN_DB
IDENTIFIED BY admindb
DEFAULT TABLESPACE TS_COURSE
QUOTA UNLIMITED ON TS_COURSE
ACCOUNT UNLOCK;

GRANT rl_admin TO ADMIN_DB;

CREATE PROFILE PADMIN LIMIT
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LIFE_TIME UNLIMITED
PASSWORD_GRACE_TIME UNLIMITED
PASSWORD_LOCK_TIME UNLIMITED;

ALTER USER ADMIN_DB PROFILE PADMIN;

GRANT ALL PRIVILEGES ON   TO rl_admin;
GRANT CONNECT TO rl_admin;
GRANT CREATE SESSION TO rl_admin;
GRANT CREATE ANY TABLE TO rl_admin;
GRANT CREATE VIEW TO rl_admin;
GRANT CREATE TRIGGER TO rl_admin;
GRANT SELECT ANY TABLE TO rl_admin;
GRANT CREATE PROCEDURE TO rl_admin;
GRANT CREATE TABLESPACE TO rl_admin;
GRANT DROP ANY TABLE TO rl_admin;
GRANT DROP ANY VIEW TO rl_admin;
GRANT EXECUTE ON ADD_HOTEL rl_admin;
GRANT EXECUTE ON DELETE_HOTEL rl_admin;
GRANT EXECUTE ON ADD_ROOM rl_admin;
GRANT EXECUTE ON DELETE_ROOM rl_admin;
GRANT EXECUTE ON UPDATE_HOTEL_RATING rl_admin;
GRANT EXECUTE ON GET_RESERVATION_STATISTICS rl_admin;
GRANT EXECUTE ON VIEW_PAYMENTS rl_admin;
GRANT EXECUTE ON CONFIRM_PAYMENT rl_admin;
GRANT EXECUTE ON VIEW_RESERVATIONS rl_admin;
GRANT EXECUTE ON CONFIRM_RESERVATION rl_admin;
GRANT EXECUTE ON CANCEL_RESERVATION rl_admin;
GRANT EXECUTE ON GET_ALL_USERS rl_admin;

--------user-------------
GRANT SELECT ON HOTELS TO rl_user;
GRANT EXECUTE ON BOOK_ROOM TO rl_user;
GRANT EXECUTE ON CANCEL_RESERVATION TO rl_user;
GRANT EXECUTE ON GET_MY_RESERVATIONS TO rl_user;
GRANT EXECUTE ON GET_AVAILABLE_ROOMS TO rl_user;
GRANT EXECUTE ON GET_RESERVATION_BILL TO rl_user;
GRANT EXECUTE ON GET_ROOMS_BY_HOTEL TO rl_user;
GRANT EXECUTE ON GET_AVAILABLE_ROOMS_IN_HOTEL TO rl_user;

GRANT CREATE SESSION
	TO rl_user;

CREATE USER USER_DB
IDENTIFIED BY userdb
DEFAULT TABLESPACE TS_COURSE
QUOTA UNLIMITED ON TS_COURSE
ACCOUNT UNLOCK;

GRANT rl_user TO USER_DB;

CREATE PROFILE PUSER LIMIT
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LIFE_TIME UNLIMITED
PASSWORD_GRACE_TIME UNLIMITED
PASSWORD_LOCK_TIME UNLIMITED;

ALTER USER USER_DB PROFILE PUSER;


---------guest------

CREATE USER GUEST_DB
IDENTIFIED BY guestdb
DEFAULT TABLESPACE TS_COURSE
QUOTA UNLIMITED ON TS_COURSE
ACCOUNT UNLOCK;
GRANT rl_guest TO GUEST_DB;

GRANT EXECUTE ON GET_ALL_USERS TO rl_guest;
GRANT EXECUTE ON GET_ALL_HOTELS TO rl_guest;
GRANT EXECUTE ON GET_ROOMS_BY_HOTEL TO rl_guest;
GRANT EXECUTE ON GET_AVAILABLE_ROOMS_IN_HOTEL TO rl_guest;
GRANT EXECUTE ON get_hotel_rating_in_city TO rl_guest;
GRANT EXECUTE ON get_room_type TO rl_guest;
GRANT EXECUTE ON get_room_price TO rl_guest;
GRANT EXECUTE ON get_room_availability TO rl_guest;


GRANT CREATE SESSION
	TO rl_guest;