--табличные пространства

CREATE TABLESPACE TS_COURSE
DATAFILE 'D:\KURSORACLE\TS_COURSE.DBF'
SIZE 20M
AUTOEXTEND ON NEXT 1M
MAXSIZE 2048M;

CREATE TABLESPACE TS_USER
DATAFILE 'D:\KURSORACLE\TS_USER.dbf'
SIZE 100M
AUTOEXTEND ON;

CREATE TABLESPACE TS_HOTELS
DATAFILE 'D:\KURSORACLE\TS_HOTELS.dbf'
SIZE 100M
AUTOEXTEND ON;

CREATE TABLESPACE TS_RESERVATION
DATAFILE 'D:\KURSORACLE\TS_RESERVATION.dbf'
SIZE 100M
AUTOEXTEND ON;

--таблицы
CREATE TABLE CUSTOMERS (
   ID_CUSTOM NUMBER(10) PRIMARY KEY,
   NAME VARCHAR2(50) NOT NULL,
   SURNAME VARCHAR2(50) NOT NULL,
   EMAIL VARCHAR2(50) NOT NULL UNIQUE,
   PHONE_NUM VARCHAR2(20) NOT NULL UNIQUE,
   LOGIN VARCHAR2(20) NOT NULL UNIQUE
)TABLESPACE TS_USER;


CREATE TABLE ROLE(
    LOGIN NUMBER(10) PRIMARY KEY,
    STATUS VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(50) NOT NULL
)TABLESPACE TS_USER;


CREATE TABLE PAYMENTS(
    ID_PAY NUMBER(10) PRIMARY KEY,
    ID_RESERV NUMBER(10),
    SUM_PAY NUMBER(10, 2) NOT NULL,
    STATUS VARCHAR2(50), 
    CONSTRAINT FK_ID_RESERV FOREIGN KEY (ID_RESERV) REFERENCES RESERVATIONS(ID_RESERV)
)TABLESPACE TS_RESERVATION;


CREATE TABLE RESERVATIONS(
    ID_RESERV NUMBER(10) PRIMARY KEY,
    ID_CUSTOM NUMBER(10),
    ID_NUM NUMBER(10),
    STATUS VARCHAR2(50),
    DATE_A DATE NOT NULL,
    DATE_D DATE NOT NULL,
    CONSTRAINT FK_CUSTOM FOREIGN KEY (ID_CUSTOM) REFERENCES CUSTOMERS(ID_CUSTOM),
    CONSTRAINT FK_NUM FOREIGN KEY (ID_NUM) REFERENCES ROOMS(ID_NUM)
)TABLESPACE TS_RESERVATION;


CREATE TABLE HOTELS(
    ID_HOT NUMBER(10) PRIMARY KEY,
    NAME_HOT VARCHAR2(50),
    CITY VARCHAR2(50),
    ADRESS VARCHAR2(50),
    RATING VARCHAR2(50)
)TABLESPACE TS_HOTELS;


CREATE TABLE ROOMS(
    ID_NUM NUMBER(10) PRIMARY KEY,
    ID_HOT NUMBER(10) ,
    TYPE VARCHAR2(50),
    PRICE NUMBER(10,2),
    AVAILABILITY VARCHAR2(50),
    NUM_OF_ROOM NUMBER(10),

CONSTRAINT FK_ID_HOT FOREIGN KEY (ID_HOT) REFERENCES HOTELS(ID_HOT)

)TABLESPACE TS_HOTELS;

