CREATE OR REPLACE VIEW RESERVATION_SUMMARY AS
SELECT
    r.ID_RESERV,
    c.NAME AS CUSTOMER_NAME,
    c.SURNAME AS CUSTOMER_SURNAME,
    c.EMAIL AS CUSTOMER_EMAIL,
    h.NAME_HOT AS HOTEL_NAME,
    h.CITY AS HOTEL_CITY,
    rm.TYPE AS ROOM_TYPE,
    rm.PRICE AS ROOM_PRICE,
    r.STATUS AS RESERVATION_STATUS,
    r.DATE_A AS DATE_ARRIVAL,
    r.DATE_D AS DATE_DEPARTURE
FROM
    RESERVATIONS r
    JOIN CUSTOMERS c ON r.ID_CUSTOM = c.ID_CUSTOM
    JOIN ROOMS rm ON r.ID_NUM = rm.ID_NUM
    JOIN HOTELS h ON rm.ID_HOT = h.ID_HOT;


SELECT * FROM RESERVATION_SUMMARY WHERE HOTEL_CITY = 'Дубай' AND RESERVATION_STATUS = 'Подтверждено';
